### PR TITLE
Improve README massively.

### PR DESCRIPTION
**Pull request by AnalogFeelings**
nsg sucks at readmes :trollface:

### CODE REVIEW

**Comment by AnalogFeelings** [comment]
hold on hold on dont merge yet

**Comment by AnalogFeelings** [comment]
okay ready

**Comment by NSG650** [comment]
x86_64-elf-gcc is required not gcc. Please make the required change.

**Comment by AnalogFeelings** [comment]
> x86_64-elf-gcc is required not gcc. Please make the required change.

neptune literally told me you only need normal gcc 🤨

**Comment by Neptune650** [comment]
LGTM.

**Pull request merged**
